name: Update Parent Repo

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: destinedcodes/git-submodules-practice
          path: ./git-submodules-practice
          submodules: recursive
          token: ${{ secrets.my_pat }}

      - name: Show Working directory
        run: |
          cd ./git-submodules-practice
          git submodule update --init --recursive --checkout -f --remote
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git commit -am "ci: ${{github.event.client_payload.module}} - ${{github.event.client_payload.sha}}"
          git push
